GG-4: Implemented AccrualClient
0loff/grade_gophermart pull request #4
Opened 2023-12-23 09:22 UTC by 0loff

2023-12-26 23:11 UTC, capsulated requested changes
Много замечаний по используемому подходу, может я что-то не так понял, но лучше уточнить, какой именно подход используется и по какому принципу.

Нужно всё же изначально договорится по структуре проекта. 

Привествуются ответы на комментарии и, скорее всего, лучше 1-1 назначить, пробежимся по проекту, ты сможешь детально рассказать про используемый подход, может бОльшая часть прояснится

По времени звонка пиши в директ в пачке, так как calendly я обновлю уже после празников

2023-12-26 23:11 UTC, capsulated commented on balance/delivery/http/handler.go
`delivery` - очень странное имя пакета, при чтении не ясно что это. В hexogonal архитектуре знаю DTO, но судя по содержимому это не оно.

Также, по структуре папок (пакетов): почему accrual и logger в internal, остальные пакеты вне internal, а pkg только encryptor? `package` лучше отдельным репозиторием создать, так как почти всегда 
переиспользуемые пакеты и бизнесовые микросервисы в разных репозиториях. Может всё в internal сделать? А для encryptor можно вообще второй go проект создать, а текущем просто импортировать через go get

2023-12-26 23:11 UTC, capsulated commented on balance/delivery/http/register.go
`delivery` - что за паттерн? В паре видео на ютубе видел такое, но какого-то описания в виде принципа/подхода/паттерна так и не нашёл

2023-12-26 23:11 UTC, capsulated commented on balance/usecase.go
> +type UseCase interface {
Я так понимаю используется определённый шаблон, либо Clean Architecture, либо DDD. Для этого, думаю, лучше в [readme.md](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams) добавить схемку с организациеи объектов и описаниемы выбранного подхода. 

Реализовывать подобные подходы возможно по-разному, поэтому необходимо заранее зафиксировать, правил какого подхода придерживаться, а какие правила не применяются.

В текущей реализации получается есть пакет `balance` и также есть модель в пакете `models` с таким же именем. Судя по нейменгу `usecase`, то должны быть `entity` и `repository`, а их тут нет. Поэтому нужно какое-то описание в readme каким образом всё структуировано

2023-12-26 23:11 UTC, capsulated commented on balance/usecase/usecase.go
> +func (b BalanceUseCase) GetUserBalance(ctx context.Context, uuid string) (models.Balance, error) {
Ресивер тут по значению передаётся, почему? И когда нужно передавать по значению, а когда по указателю: `b *BalanceUseCase`?

2023-12-26 23:11 UTC, capsulated commented on internal/accrualClient/accrualClient.go
> +package accrualclient
Можно его в одно слово `accrual` переименовать. В go поощрается простое имя пакета в одно слово. И в место создания пакета из двух слов предлагается поделить на два пакета

2023-12-26 23:11 UTC, capsulated commented on internal/accrualClient/accrualClient.go
> +	service := &AccrualClient{
Для локальных переменных лучше использовать те же имена, что у типа, только с маленькой буквы или сокращение. Если использовать другое слово (`service` для `AccrualClient`), то очень сбивает с толку

2023-12-26 23:11 UTC, capsulated commented on internal/accrualClient/accrualClient.go
> +	go service.AccrualManager(service.OrderCh)
`go accrual.Manage()` или `go accrual.Work()` или `go accrual.Run()` для воркеров подходит. Или что-то подобное. Чтобы сразу было понятно, что это какой-то процесс в го-рутине / в бесконечном цикле, а не экземпляр объекта

2023-12-26 23:11 UTC, capsulated commented on internal/logger/logger.go
> +func RequestLogger(h http.Handler) http.Handler {
Это не должно быть в пакете logger. Лучше пакет/пакеты `middleware`. На крайний случай где-то в хендлерах или в роутере. Но точно не в пакете логгера

2023-12-26 23:11 UTC, capsulated commented on internal/logger/responseWriter.go
`responseWriter` точно в пакете с хендлерми должен быть. В логгере не должно быть импорта пакета `http`

2023-12-26 23:11 UTC, capsulated commented on models/accrual.go
> +type AccrualResponse struct {
Так как это `response`, то скорее всего это должен бы локальный тип в пакете `handler`. Хотя может быть глобальный entity, а `usecase` преобразования в **json** как отдельная сущность

2023-12-26 23:11 UTC, capsulated commented on models/balance.go
> +package models
Тогда, скорее, entity,  models. Как отметил выше, нужно описание используемого подхода

2023-12-26 23:11 UTC, capsulated commented on order/delivery/http/handler.go
> +	if err = h.useCase.SetOrder(r.Context(), *Order); err != nil {
Запись ордера - это usecase хендлера? По идее, это должен быть usecase репозитория, нет?

2023-12-26 23:11 UTC, capsulated commented on order/delivery/http/handler.go
> +		case errors.Is(err, order.ErrInvalidOrderNumber):
А ошибки из пакета `order`? Очень вероятно, что тут ошибки репозитория, а у хендлеров могут быть свои ошибки, связанные именно с http ответами и всё что связано с хендлерами. Я могу ошибаться, так как необходимо описание подхода

2023-12-26 23:11 UTC, capsulated commented on order/delivery/http/register.go
Всё равно не пойму, почему delevery пакет добавлен. Мжет же быть просто пакет `router`. И читаться будет проще и структура проще. Если не согласен - ответ на комментарий только привестсвтуется

2023-12-26 23:11 UTC, capsulated commented on order/error.go
> +import "errors"
Ошибки лучше по слоям абстракций определить, то есть ошибки хендлеров, ошибки бд, ошибки accrual в запросах

2023-12-26 23:11 UTC, capsulated commented on order/repository.go
> +type Repository interface {
Это методы для репозиторя только для ордера? Разве это не repository usecase?

2023-12-26 23:11 UTC, capsulated commented on order/repository/postgres/order.go
> +func (r OrderRepository) CreateTable() {
Это лучше либо отдельными init.sql скриптом реализовать, либо в дополнительный usecase репозитория, что-то типа usecase инициализации

2023-12-26 23:11 UTC, capsulated commented on server/app.go
> +func NewApp(cfg config.Config) *App {
`App` не очень удачный нейминг, так как стандартная папка в проектах golang `app` отвечает за экземпляр приложения. А в `cmd` (сокращение от command) - запуск этих приложений в зафисимости от флагов или конфига. Это похоже на server gophermart

2023-12-26 23:11 UTC, capsulated commented on server/app.go
> +	router := chi.NewRouter()
Конструктор роутера необходимо вызвать до старта приложения. В идеале, передать указатель на роутер в конструктор сервера. И после успешной инициализации запустить сервер

2023-12-26 23:11 UTC, capsulated commented on server/app.go
> +	signal.Notify(quit, os.Interrupt, os.Interrupt)
Это точно должно быть в папке `app`. В упрощенном виде - в `cmd`, если `app` нет в проекте. Это же упрощенный gracefully shutdown

2023-12-26 23:11 UTC, capsulated commented on server/app.go
> +func initDB(DSN string) (*pgxpool.Pool, error) {
Это же конструктор базы данных. Префикс `New` должен быть. И находится он должен в `repository` пакете, а не в `server`

2023-12-27 12:23 UTC, 0loff commented on balance/delivery/http/handler.go
delivery - абстрактный слой доменной области, отвечающий за доставку контента при обращении к API endpoints;

accrual и logger - служебные внутренние пакеты, используемые исключительно внутри приложения без возможности распространения на иные приложения и репозитории GitHub;

user, order, balance - абстрактные доменные области приложения;

config - реализация паттерна builder для подготовки конфигурации приложения при развертывании;

models - общее описание моделей доменных сущностей;

encryptor - пакет, используемый в служебных целях для шифрования и хранения сенсетивных данных. Один из главных принципов использования - заменяемость. В pkg может храниться множество различных encryptor's в качестве подключаемых и легко заменяемых пакетов.

2023-12-27 12:28 UTC, 0loff commented on balance/delivery/http/register.go
```delivery``` - скорее реализация собственного видения разбиения доменных областей на абстрактные слои.

2023-12-27 12:32 UTC, 0loff commented on balance/usecase.go
> +type UseCase interface {
Все верно, это попытка реализации собственного видения шаблона Clean Architecture.

Добавил небольшое описание в readme. При необходимости могу расширить, однако в текущих условиях выглядит избыточно.

2023-12-27 12:43 UTC, 0loff commented on balance/usecase/usecase.go
> +func (b BalanceUseCase) GetUserBalance(ctx context.Context, uuid string) (models.Balance, error) {
В данном случае экземпляр сервиса BalanceUseCase создается при запуске и инициализации приложения и по сути все время мы работаем именно с этим экземпляром. Поэтому ресивер должен передаваться по указателю в метод. Исправил.

2023-12-27 12:57 UTC, 0loff commented on internal/accrualClient/accrualClient.go
> +	go service.AccrualManager(service.OrderCh)
Хорошее замечание, спасибо. Довольно не просто перестраиваться приходя с ООП языков.

2023-12-27 13:06 UTC, 0loff commented on internal/logger/logger.go
> +func RequestLogger(h http.Handler) http.Handler {
Logger реализовывал согласно и в соотвествии с теорией предлагаемой на платформе. [Спринт 2. Логирование через middleware](https://practicum.yandex.ru/learn/go-advanced/courses/84f4d4db-15f7-4efd-9c53-1d7e1f27ba14/sprints/139865/topics/45c790ba-bd94-4f8f-8566-29936ec5060e/lessons/f0c2c160-dacb-4b45-b960-fcd8079896d0/)

2023-12-27 13:07 UTC, 0loff commented on internal/logger/responseWriter.go
Актуален [предидущий комментарий](https://github.com/0loff/grade_gophermart/pull/4#discussion_r1436634481)

2023-12-27 14:39 UTC, 0loff commented on order/delivery/http/handler.go
> +	if err = h.useCase.SetOrder(r.Context(), *Order); err != nil {
В качестве ```usecase``` хэндлера передается ```order.UseCase``` как сервис, который взаимодействует с репозиторием. То есть SetOrder это метод сервиса, описанный в соответствующем интерфейсе и реализующий собственную логику. В свою очередь репозиторий обладает методом InsertOrder, описанным в соответствующем интерфейсе репозитория. И уже он взаимодействует с БД.

2023-12-27 14:46 UTC, 0loff commented on order/delivery/http/handler.go
> +		case errors.Is(err, order.ErrInvalidOrderNumber):
Ошибки объединены в пакетах и относятся к соответствующим доменным областям (сущностям).

2023-12-27 14:47 UTC, 0loff commented on order/delivery/http/register.go
Постарался развернуто ответить в [первом комментарии](https://github.com/0loff/grade_gophermart/pull/4#discussion_r1437008592)

2023-12-27 14:50 UTC, 0loff commented on order/error.go
> +import "errors"
[Актуален данный комментарий](https://github.com/0loff/grade_gophermart/pull/4#discussion_r1437085913)

2023-12-27 14:52 UTC, 0loff commented on order/repository.go
> +type Repository interface {
Верно, это интерфейс методов репозитория доменной области order.

2023-12-28 11:28 UTC, 0loff commented on models/accrual.go
> +type AccrualResponse struct {
При вынесении в ```handler``` accrual будет увеличена связанность сущностей, т.к. придется импортировать accrual в интерфейс, а так же в сам репозиторий order.

2023-12-28 11:30 UTC, 0loff commented on models/balance.go
> +package models
Добавил описание применяемого подхода в README.md

2023-12-28 11:37 UTC, 0loff commented on internal/accrualClient/accrualClient.go
> +	service := &AccrualClient{
Подход с отдельным init.sql скриптом действительно выглядит подходящим, однако в условиях выполняемой задачи решил ограничиться созданием таблиц при инициализации репозиториев доменных сущностей.

2023-12-28 11:47 UTC, 0loff commented on internal/accrualClient/accrualClient.go
> +	go service.AccrualManager(service.OrderCh)
Изменил нэйминг на Gophermart, а так же вызов на NewGophermart.

2023-12-28 13:46 UTC, 0loff commented on internal/logger/responseWriter.go
Вынес shutdown в отдельный метод сервера, однако не вижу смысла разделять метод run c горутиной запуска сервера от его прерывания.

2023-12-28 13:51 UTC, 0loff commented on models/accrual.go
> +type AccrualResponse struct {
Добавил префикс ```NewDB``` конструктору БД. Инициализацию оставил в server т.к. в текщуей реализации у нас есть несколько репозиториев в разных доменных сущностях, взаимодействующих с одним соединением с БД.

2023-12-28 21:11 UTC, 0loff commented on server/app.go
> +func NewApp(cfg config.Config) *App {
Изменил нэйминг на Gophermart, а так же вызов на NewGophermart.

2023-12-28 21:12 UTC, 0loff commented on server/app.go
> +	router := chi.NewRouter()
Вынес инициализацию роутера с передачей по указателю в конструктор сервера.

2023-12-28 21:13 UTC, 0loff commented on server/app.go
> +	signal.Notify(quit, os.Interrupt, os.Interrupt)
Вынес shutdown в отдельный метод сервера, однако не вижу смысла разделять метод run c горутиной запуска сервера от его прерывания.

2023-12-28 21:14 UTC, 0loff commented on server/app.go
> +func initDB(DSN string) (*pgxpool.Pool, error) {
Добавил префикс NewDB конструктору БД. Инициализацию оставил в server т.к. в текщуей реализации у нас есть несколько репозиториев в разных доменных сущностях, взаимодействующих с одним соединением с БД.

2023-12-28 21:16 UTC, 0loff commented on order/repository/postgres/order.go
> +func (r OrderRepository) CreateTable() {
Подход с отдельным init.sql скриптом действительно выглядит подходящим, однако в условиях выполняемой задачи решил ограничиться созданием таблиц при инициализации репозиториев доменных сущностей.

2023-12-29 19:25 UTC, capsulated commented on internal/logger/logger.go
> +func RequestLogger(h http.Handler) http.Handler {
Ссылки с платформы работать не будут. И в спринт 2 не могу найти темы про логгирование через middleware. Яркий пример: Спринт: 1 → Тема: net/http → Урок: 7. HTTP Библиотеки → Роутер Chi -> Middleware → Задание `2`, `4`. 

Также, можно посмотреть на [middleware бибилиотеки chi](https://github.com/go-chi/chi/tree/master/middleware)

2023-12-29 19:31 UTC, capsulated commented on internal/logger/responseWriter.go
Аналогично)

В любом случае, пакет логгер не должен содержать зависимостей на http. В теории много примеров, писать код один-в-один из некоторых примеров из теории, так как предоставленные примеры могут быть демонстрационными.

Скинь, пожалуйста, в пачку, точнее Спринт, Тему, Урок и т.п., создам тикет, если оно там так

2023-12-29 19:33 UTC, capsulated commented on models/accrual.go
> +type AccrualResponse struct {
А, в данном случае, да, accrualResponse - это же ответ от сторонней системы бонусов accrua, правильно?  То есть, от клиента. А handlers - это вообще серверные сущности

2023-12-29 19:35 UTC, capsulated commented on order/delivery/http/handler.go
> +	if err = h.useCase.SetOrder(r.Context(), *Order); err != nil {
Да, это обсудили, как раз, на звонке. Тут, грубо говоря, `h.` это `orderHandler.`

2023-12-29 19:37 UTC, capsulated commented on order/delivery/http/handler.go
> +		case errors.Is(err, order.ErrInvalidOrderNumber):
Вооот, ошибки делятся не по доменным областям, а по слоям абстракции - ошибки БД на уровне БД, ошибки http на этом уровне, а ошибки доменной области - это скажем `не смог преобразовать в JSON`, тоесть, ошибки непосредственно самой entity и его собственным методов (преобразований, например)

2023-12-29 19:39 UTC, capsulated commented on order/repository.go
> +type Repository interface {
Также, обсудили на звонке, это интерфейс в пакете `order`

2023-12-29 19:44 UTC, capsulated commented on server/app.go
> +func NewApp(cfg config.Config) *App {
Эх, всё равно какой-то странный объект получился, вроде сервер, а вроде и сервис `gophermart`. Немного перемешалась логика. В идеале в `gophermart` - это сервис, а сервер, как отдельный указать на экземпляр  передавать в конструктор `gophermart`'а

2023-12-29 19:52 UTC, capsulated commented on server/gophermart.go
> +func NewDB(DSN string) (*pgxpool.Pool, error) {
А здесь конструктор `*pgxpool.Pool`... Можно же передать пул соединений также в конструктор гофермарта и там с ним работать. А вообще, по CleanArchitecture - это должен быть контроллер над Postgres

2023-12-29 19:52 UTC, capsulated commented on server/app.go
> +	router := chi.NewRouter()
Вообще, в идеале, в папке `app` нужно создавать, грубо говоря, наш GophermartApp, и там, на одном уровне, вызывать конструкторы и передавать в зависимости. В идеале IoC/DI/DIC, но без этого - это всё создавать на уровне приложения, либо, в упрощенном виде, просто в `cmd`.

Когда вызывается конструктор в конструкторе - это звоночек, всегда надо выносить на уровень выше и передать в параметры конструктора через интерфейс, если это возможно. Если нет - надо смотреть, что за паттерн

2023-12-29 19:53 UTC, capsulated commented on server/app.go
> +func initDB(DSN string) (*pgxpool.Pool, error) {
А почему в пакете `server`? Это точно неправильно, конструктор базы данных должен быть в пакете базы данных

2023-12-29 19:56 UTC, capsulated commented on internal/accrualClient/accrualClient.go
> +	go service.AccrualManager(service.OrderCh)
Go по факту сохраняет все паттерны ООП. На C++ тоже можно coroutines запускать и различные асинхронные воркеры, на python также есть пакет async. Тут скорее нейминг метода должен быть глаголом, а поля и сами типы - именами существительными

2023-12-29 19:58 UTC, capsulated commented on server/app.go
> +	signal.Notify(quit, os.Interrupt, os.Interrupt)
Так тут прерывание всего приложения обрабатывается, а только сервера. Тогда, необходимо рассмотреть кейс, где прерывается работа сервера, а остальные сервисы (запросы к accrual и тп) не должны останавливаться

2023-12-29 20:02 UTC, capsulated requested changes
На половине комментов, все же, добавил ответы. Почитай, пожалуйста

В принципе, минимальный объём для сдачи уже есть. Если есть желание немного оптимизировать - будет супер, а если нет времени/желания - пиши сообщение в пачку, что хотелось бы поскорее сдать, и присылай на проверку - приму работу

2023-12-30 16:53 UTC, 0loff commented on internal/accrualClient/accrualClient.go
> +	go service.AccrualManager(service.OrderCh)
Изменил на ```go accrual.Run()```

2023-12-30 17:29 UTC, 0loff commented on internal/logger/logger.go
> +func RequestLogger(h http.Handler) http.Handler {
Становиться сложно дискутировать когда аргументы не принимаются ввиду не открывающейся ссылки. Попробуем в скриншоты =) ?

![screen-1](https://github.com/0loff/grade_gophermart/assets/50675845/e3ad90e5-ebeb-402e-9e4a-56d7be05a168)
![screen-2](https://github.com/0loff/grade_gophermart/assets/50675845/7b01d8dc-b9c1-4064-83bf-5bdcd553f737)
![screen-3](https://github.com/0loff/grade_gophermart/assets/50675845/80e4f284-340b-4879-9a3c-19b292c7631a)
![screen-4](https://github.com/0loff/grade_gophermart/assets/50675845/bc386db8-ab7f-47a0-8114-2f3a3dec48b4)

2023-12-30 17:49 UTC, 0loff commented on internal/logger/responseWriter.go
Пожалуй еще одна ссылка на [предидущий комментарий](https://github.com/0loff/grade_gophermart/pull/4#discussion_r1438663356).


Полагаю теория на платформе подается как раз с целью быть применимой на практике (скажем, в выпускном проекте). К тому же, реализация логирования через middleware в теоретической части выглядит не как множество разрозненных примеров, а как основной мотив для разбора и реализации в части спринта.

P.S. Отказываясь от идей реализации, изложенных в теоретической части, мы ставим под сомнение как теорию, преподаваемую на платформе, так и саму платформу.

2023-12-31 12:47 UTC, 0loff commented on order/delivery/http/handler.go
> +		case errors.Is(err, order.ErrInvalidOrderNumber):
Ошибки НЕ делятся по доменным областям. Они объединены (сгруппированы) в ```error.go``` своей доменной области. А выбрасываются они ровно в тех слоях абстракции, где необходим их вызов. Ошибки взаимодействия с БД - из репозитория, ошибки бизнес-логики - из usecase (service). Ошибки handler's из соответствующего слоя ```delivery```. Хотя в последнем случае они чаще там отлавливаются и обрабатываются с выдачей соответствующего статуса, нежели выбрасывают какое то особенное исключение. Ко всему прочему zap логгер в своем stacktrace указывает на точное место, откуда была вызвана ошибка.

2023-12-31 12:52 UTC, 0loff commented on order/error.go
> +import "errors"
Ошибки вызываются в соответствующих слоях абстракции. Сгруппированы же и хранятся в одном месте, что гораздо удобнее раскладывания их в отдельных слоях абстракции в виде единственной строки выбрасываемой ошибки.

2023-12-31 13:23 UTC, 0loff commented on server/app.go
> +func NewApp(cfg config.Config) *App {
И все же, следуя спецификации технического задания ```gophermart``` - это сервер.
![Снимок экрана 2023-12-31 в 16 16 01](https://github.com/0loff/grade_gophermart/assets/50675845/f0c5406e-f107-4e73-aceb-6e824fa18b03)

2023-12-31 13:27 UTC, 0loff commented on server/app.go
> +	router := chi.NewRouter()
Идея понятна, однако в текущих условиях, а так же ограниченности реализуемого функционала в рамках т/з выпускной работы выглядит избыточно.

2023-12-31 13:35 UTC, 0loff commented on server/app.go
> +	signal.Notify(quit, os.Interrupt, os.Interrupt)
> Тогда, необходимо рассмотреть кейс, где прерывается работа сервера, а остальные сервисы (запросы к accrual и тп) не должны останавливаться

Мне кажется или подобные требования к устойчивости приложения, а так же к его аптайму должны быть отражены в техническом задании? На текущий момент времени, мне гораздо выгоднее выпилить мою вольность с попыткой в ```shutdown``` чем пересматривать архитектуру решения ввиду возникновения новых вводных.

2023-12-31 16:25 UTC, 0loff commented on server/app.go
> +func initDB(DSN string) (*pgxpool.Pool, error) {
Вынес конструктор соединения с БД в отдельный пакет ```internal/database/postgres```.

2023-12-31 16:38 UTC, 0loff commented on server/gophermart.go
> +func NewDB(DSN string) (*pgxpool.Pool, error) {
Не очень понятно в чем здесь проблема на текущий момент. В конструкторе мы создаем пул соединений, который в результате возвращаем на уровень инициализации приложения и передаем в несколько репозиториев для взаимодействия с БД. Естественно к решению подобных архитектурных вопросов можно подходить по разному. Все зависит от сложности выполняемой задачи и закладываемой архитектуры. В рамках текущего задания и предлагаемого т/з полагаю реализованный подход вполне оправдан.

2024-01-09 22:15 UTC, capsulated approved these changes
В общем всё хорошо

Пару коментов всё равно написал. По организации объектов, на мой вкус, я бы некоторые моменты переделал. Будет желание - записывайся на 1-1, обсудим

Работу принял, всё супер

2024-01-09 22:15 UTC, capsulated commented on server/gophermart.go
> +type Gophermart struct {
Это скорее в `app` пакет

2024-01-09 22:15 UTC, capsulated commented on balance/delivery/http/handler.go
А так и не разобрался, почему пакет `balance` в корне приложения, а всё остальное в `internal` 🤔

2024-01-09 22:18 UTC, capsulated approved these changes
В общем всё хорошо

Пару коментов всё равно написал. По организации объектов, на мой вкус, я бы некоторые моменты переделал. Будет желание - записывайся на 1-1, обсудим

Работу принял

2024-01-11 18:15 UTC, 0loff commented on balance/delivery/http/handler.go
В корне не только ```balance```, еще ```user``` и ```order```. Подробнее описывал в [первом комментарии](https://github.com/0loff/grade_gophermart/pull/4#discussion_r1437008592). Это абстрактные доменные области (сущности) приложения. 

В ```internal``` содержаться только внутренние служебные пакеты, которые не планируется использовать где то вне приложения.

2024-03-13 07:07 UTC, merged